### ISSUE TITLE
1.21 update

### ISSUE THREAD

**Issue by Lunethia** [jodeks-datapacks/AFK-Announcer#1]
Hey!
If not already in progress, could this be updated for 1.21?
If already in progress, could a quick confirmation that it's WIP be posted here?

Thanks!

**Comment by Jodekq** [comment]
Yup, already in progress. Will be done very soon.

**Comment by Jodekq** [comment]
Version for 1.21 released!

**Comment by Lunethia** [comment]
based dev
cheers
